### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by HZooly**
Add brew and alphabetical order on Utilities

### CODE REVIEW

**Comment by nikivdev** [comment]
Thank you. 💜

**Comment by nikivdev** [comment]
I am writing a Python script to capitalise all entries. Hope to add it soon.

**Comment by HZooly** [comment]
Ok that's nice! Maybe you could include an alphabetical sort?

**Comment by nikivdev** [comment]
I can do that too. For [books](https://github.com/learn-anything/books) though I want to sort by year.

**Comment by HZooly** [comment]
Why not, but you'll have to convert dates like `09` to `2009` before I guess.

**Comment by nikivdev** [comment]
Yep. I already started doing that. But I need a script because there are too many books.

**Pull request merged**
